on: push

name: Build, test and deploy
jobs:
  check_codestyle:
    name: Codestyle
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.3
      - name: Composer install
        run: composer install
      - name: Check codestyle
        run: vendor/bin/phpcs
  static_code_analysis:
    name: Static Code Analysis
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.3
      - name: Composer install
        run: composer install
      - name: Install PHPUnit
        run: ./bin/phpunit --version
      - name: Static code analysis
        run: vendor/bin/phpstan analyse
  unit_tests:
    name: Unit tests
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.3
      - name: Composer install
        run: composer install
      - name: Unit tests
        run: phpdbg -qrr ./bin/phpunit --coverage-clover=coverage/unit.xml
      - name: Upload code coverage
        run: bash <(curl -s https://codecov.io/bash) -f coverage/unit.xml -t ${{ secrets.CODECOV_TOKEN }}
  deploy:
    name: Serverless deploy
    if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop') && !github.event.deleted
    needs:
      - check_codestyle
      - static_code_analysis
      - unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.3
      - name: Composer install
        run: composer install --no-dev --optimize-autoloader
      - name: Deploy to dev
        if: github.ref == 'refs/heads/develop'
        uses: serverless/github-action@master
        with:
          args: deploy --stage=dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      - name: Deploy to prod
        if: github.ref == 'refs/heads/master'
        uses: serverless/github-action@master
        with:
          args: deploy --stage=prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
